import { loadLegacyRendererScript } from '../legacy-loader';
import { createBoardLegacyBindingsUtils } from './legacy-bindings-utils';
import { createBoardLegacyBindingsActionUtils } from './legacy-bindings-action-utils';
import { createBoardLegacyBootstrapUtils } from './legacy-bootstrap-utils';
import { createBoardLegacyBootstrapOrchestrationUtils } from './legacy-bootstrap-orchestration-utils';
import { createBoardLegacyCaptureUtils } from './legacy-capture-utils';
import { createBoardLegacyCaptureFlowUtils } from './legacy-capture-flow-utils';
import { createBoardLegacyCaptureOrchestrationUtils } from './legacy-capture-orchestration-utils';
import { createBoardLegacyRuntimeCaptureHandlersUtils } from './legacy-runtime-capture-handlers-utils';
import { createBoardLegacyDialogUtils } from './legacy-dialog-utils';
import { createBoardLegacyDialogFlowUtils } from './legacy-dialog-flow-utils';
import { createBoardLegacyDialogStateUtils } from './legacy-dialog-state-utils';
import { createBoardLegacyDialogOrchestrationUtils } from './legacy-dialog-orchestration-utils';
import { createBoardLegacyRuntimeDialogHandlersUtils } from './legacy-runtime-dialog-handlers-utils';
import { createBoardLegacyEventBindingsUtils } from './legacy-event-bindings-utils';
import { createBoardLegacyItemActionUtils } from './legacy-item-action-utils';
import { createBoardLegacyItemActionsOrchestrationUtils } from './legacy-item-actions-orchestration-utils';
import { createBoardLegacyItemMetadataActionsUtils } from './legacy-item-metadata-actions-utils';
import { createBoardLegacyItemUtils } from './legacy-item-utils';
import { createBoardLegacyKeyboardUtils } from './legacy-keyboard-utils';
import { createBoardLegacyLifecycleEventUtils } from './legacy-lifecycle-event-utils';
import { createBoardLegacyListRenderUtils } from './legacy-list-render-utils';
import { createBoardLegacyListActionUtils } from './legacy-list-action-utils';
import { createBoardLegacyListOrchestrationUtils } from './legacy-list-orchestration-utils';
import { createBoardLegacyLoadSearchUtils } from './legacy-load-search-utils';
import { createBoardLegacyLoadSearchOrchestrationUtils } from './legacy-load-search-orchestration-utils';
import { createBoardLegacyPreviewControlsUtils } from './legacy-preview-controls-utils';
import { createBoardLegacyPreviewActionUtils } from './legacy-preview-action-utils';
import { createBoardLegacyPreviewLayoutUtils } from './legacy-preview-layout-utils';
import { createBoardLegacyPreviewMediaUtils } from './legacy-preview-media-utils';
import { createBoardLegacyPreviewMountUtils } from './legacy-preview-mount-utils';
import { createBoardLegacyPreviewMessageUtils } from './legacy-preview-message-utils';
import { createBoardLegacyPreviewMessageOrchestrationUtils } from './legacy-preview-message-orchestration-utils';
import { createBoardLegacyPreviewRenderOrchestrationUtils } from './legacy-preview-render-orchestration-utils';
import { createBoardLegacyPreviewRenderStateUtils } from './legacy-preview-render-state-utils';
import { createBoardLegacyRenderUtils } from './legacy-render-utils';
import { createBoardLegacyRuntimeContextUtils } from './legacy-runtime-context-utils';
import { createBoardLegacyRuntimeFoundationUtils } from './legacy-runtime-foundation-utils';
import { createBoardLegacyRuntimeInputsUtils } from './legacy-runtime-inputs-utils';
import { createBoardLegacyRuntimeItemLoadHandlersUtils } from './legacy-runtime-item-load-handlers-utils';
import { createBoardLegacyRuntimeLifecycleUtils } from './legacy-runtime-lifecycle-utils';
import { createBoardLegacyRuntimePreviewListHandlersUtils } from './legacy-runtime-preview-list-handlers-utils';
import { createBoardLegacySearchUtils } from './legacy-search-utils';
import { createBoardLegacySelectionUtils } from './legacy-selection-utils';
import { createBoardLegacyShortcutUtils } from './legacy-shortcut-utils';
import { createBoardLegacyStatusUtils } from './legacy-status-utils';
import { createBoardLegacyWireupRegistrationUtils } from './legacy-wireup-registration-utils';
import { createBoardLegacyWireupRuntimeUtils } from './legacy-wireup-runtime-utils';
import { createBoardLegacyWireupUtils } from './legacy-wireup-utils';
import { createBoardLegacyUtils } from './legacy-utils';

window.__boardLegacyUtils = createBoardLegacyUtils();
window.__boardLegacyShortcutUtils = createBoardLegacyShortcutUtils();
window.__boardLegacyBindingsUtils = createBoardLegacyBindingsUtils();
window.__boardLegacyBindingsActionUtils = createBoardLegacyBindingsActionUtils();
window.__boardLegacyBootstrapUtils = createBoardLegacyBootstrapUtils();
window.__boardLegacyBootstrapOrchestrationUtils = createBoardLegacyBootstrapOrchestrationUtils();
window.__boardLegacyCaptureUtils = createBoardLegacyCaptureUtils();
window.__boardLegacyCaptureFlowUtils = createBoardLegacyCaptureFlowUtils();
window.__boardLegacyCaptureOrchestrationUtils = createBoardLegacyCaptureOrchestrationUtils();
window.__boardLegacyRuntimeCaptureHandlersUtils = createBoardLegacyRuntimeCaptureHandlersUtils();
window.__boardLegacyDialogUtils = createBoardLegacyDialogUtils();
window.__boardLegacyDialogFlowUtils = createBoardLegacyDialogFlowUtils();
window.__boardLegacyDialogStateUtils = createBoardLegacyDialogStateUtils();
window.__boardLegacyDialogOrchestrationUtils = createBoardLegacyDialogOrchestrationUtils();
window.__boardLegacyRuntimeDialogHandlersUtils = createBoardLegacyRuntimeDialogHandlersUtils();
window.__boardLegacyEventBindingsUtils = createBoardLegacyEventBindingsUtils();
window.__boardLegacyItemActionUtils = createBoardLegacyItemActionUtils();
window.__boardLegacyItemActionsOrchestrationUtils = createBoardLegacyItemActionsOrchestrationUtils();
window.__boardLegacyItemMetadataActionsUtils = createBoardLegacyItemMetadataActionsUtils();
window.__boardLegacyItemUtils = createBoardLegacyItemUtils();
window.__boardLegacyKeyboardUtils = createBoardLegacyKeyboardUtils();
window.__boardLegacyLifecycleEventUtils = createBoardLegacyLifecycleEventUtils();
window.__boardLegacyListRenderUtils = createBoardLegacyListRenderUtils();
window.__boardLegacyListActionUtils = createBoardLegacyListActionUtils();
window.__boardLegacyListOrchestrationUtils = createBoardLegacyListOrchestrationUtils();
window.__boardLegacyLoadSearchUtils = createBoardLegacyLoadSearchUtils();
window.__boardLegacyLoadSearchOrchestrationUtils = createBoardLegacyLoadSearchOrchestrationUtils();
window.__boardLegacyRenderUtils = createBoardLegacyRenderUtils();
window.__boardLegacyPreviewControlsUtils = createBoardLegacyPreviewControlsUtils();
window.__boardLegacyPreviewActionUtils = createBoardLegacyPreviewActionUtils();
window.__boardLegacyPreviewLayoutUtils = createBoardLegacyPreviewLayoutUtils();
window.__boardLegacyPreviewMediaUtils = createBoardLegacyPreviewMediaUtils();
window.__boardLegacyPreviewMountUtils = createBoardLegacyPreviewMountUtils();
window.__boardLegacyPreviewMessageUtils = createBoardLegacyPreviewMessageUtils();
window.__boardLegacyPreviewMessageOrchestrationUtils = createBoardLegacyPreviewMessageOrchestrationUtils();
window.__boardLegacyPreviewRenderOrchestrationUtils = createBoardLegacyPreviewRenderOrchestrationUtils();
window.__boardLegacyPreviewRenderStateUtils = createBoardLegacyPreviewRenderStateUtils();
window.__boardLegacyRuntimeContextUtils = createBoardLegacyRuntimeContextUtils();
window.__boardLegacyRuntimeFoundationUtils = createBoardLegacyRuntimeFoundationUtils();
window.__boardLegacyRuntimeInputsUtils = createBoardLegacyRuntimeInputsUtils();
window.__boardLegacyRuntimeItemLoadHandlersUtils = createBoardLegacyRuntimeItemLoadHandlersUtils();
window.__boardLegacyRuntimeLifecycleUtils = createBoardLegacyRuntimeLifecycleUtils();
window.__boardLegacyRuntimePreviewListHandlersUtils = createBoardLegacyRuntimePreviewListHandlersUtils();
window.__boardLegacySearchUtils = createBoardLegacySearchUtils();
window.__boardLegacySelectionUtils = createBoardLegacySelectionUtils();
window.__boardLegacyStatusUtils = createBoardLegacyStatusUtils();
window.__boardLegacyWireupRegistrationUtils = createBoardLegacyWireupRegistrationUtils();
window.__boardLegacyWireupRuntimeUtils = createBoardLegacyWireupRuntimeUtils();
window.__boardLegacyWireupUtils = createBoardLegacyWireupUtils();

loadLegacyRendererScript('./board.js');
