import type { BoardLegacyBindingsUtils } from '../renderer/board/legacy-bindings-utils';
import type { BoardLegacyBindingsActionUtils } from '../renderer/board/legacy-bindings-action-utils';
import type { BoardLegacyBootstrapUtils } from '../renderer/board/legacy-bootstrap-utils';
import type { BoardLegacyBootstrapOrchestrationUtils } from '../renderer/board/legacy-bootstrap-orchestration-utils';
import type { BoardLegacyCaptureUtils } from '../renderer/board/legacy-capture-utils';
import type { BoardLegacyCaptureFlowUtils } from '../renderer/board/legacy-capture-flow-utils';
import type { BoardLegacyCaptureOrchestrationUtils } from '../renderer/board/legacy-capture-orchestration-utils';
import type { BoardLegacyRuntimeCaptureHandlersUtils } from '../renderer/board/legacy-runtime-capture-handlers-utils';
import type { BoardLegacyDialogFlowUtils } from '../renderer/board/legacy-dialog-flow-utils';
import type { BoardLegacyDialogStateUtils } from '../renderer/board/legacy-dialog-state-utils';
import type { BoardLegacyDialogOrchestrationUtils } from '../renderer/board/legacy-dialog-orchestration-utils';
import type { BoardLegacyDialogUtils } from '../renderer/board/legacy-dialog-utils';
import type { BoardLegacyRuntimeDialogHandlersUtils } from '../renderer/board/legacy-runtime-dialog-handlers-utils';
import type { BoardLegacyEventBindingsUtils } from '../renderer/board/legacy-event-bindings-utils';
import type { BoardLegacyItemActionUtils } from '../renderer/board/legacy-item-action-utils';
import type { BoardLegacyItemActionsOrchestrationUtils } from '../renderer/board/legacy-item-actions-orchestration-utils';
import type { BoardLegacyItemMetadataActionsUtils } from '../renderer/board/legacy-item-metadata-actions-utils';
import type { BoardLegacyItemUtils } from '../renderer/board/legacy-item-utils';
import type { BoardLegacyKeyboardUtils } from '../renderer/board/legacy-keyboard-utils';
import type { BoardLegacyLifecycleEventUtils } from '../renderer/board/legacy-lifecycle-event-utils';
import type { BoardLegacyListActionUtils } from '../renderer/board/legacy-list-action-utils';
import type { BoardLegacyListRenderUtils } from '../renderer/board/legacy-list-render-utils';
import type { BoardLegacyListOrchestrationUtils } from '../renderer/board/legacy-list-orchestration-utils';
import type { BoardLegacyLoadSearchUtils } from '../renderer/board/legacy-load-search-utils';
import type { BoardLegacyLoadSearchOrchestrationUtils } from '../renderer/board/legacy-load-search-orchestration-utils';
import type { BoardLegacyPreviewActionUtils } from '../renderer/board/legacy-preview-action-utils';
import type { BoardLegacyPreviewControlsUtils } from '../renderer/board/legacy-preview-controls-utils';
import type { BoardLegacyPreviewLayoutUtils } from '../renderer/board/legacy-preview-layout-utils';
import type { BoardLegacyPreviewMediaUtils } from '../renderer/board/legacy-preview-media-utils';
import type { BoardLegacyPreviewMountUtils } from '../renderer/board/legacy-preview-mount-utils';
import type { BoardLegacyPreviewMessageUtils } from '../renderer/board/legacy-preview-message-utils';
import type { BoardLegacyPreviewMessageOrchestrationUtils } from '../renderer/board/legacy-preview-message-orchestration-utils';
import type { BoardLegacyPreviewRenderOrchestrationUtils } from '../renderer/board/legacy-preview-render-orchestration-utils';
import type { BoardLegacyPreviewRenderStateUtils } from '../renderer/board/legacy-preview-render-state-utils';
import type { BoardLegacyRenderUtils } from '../renderer/board/legacy-render-utils';
import type { BoardLegacyRuntimeContextUtils } from '../renderer/board/legacy-runtime-context-utils';
import type { BoardLegacyRuntimeFoundationUtils } from '../renderer/board/legacy-runtime-foundation-utils';
import type { BoardLegacyRuntimeInputsUtils } from '../renderer/board/legacy-runtime-inputs-utils';
import type { BoardLegacyRuntimeItemLoadHandlersUtils } from '../renderer/board/legacy-runtime-item-load-handlers-utils';
import type { BoardLegacyRuntimeLifecycleUtils } from '../renderer/board/legacy-runtime-lifecycle-utils';
import type { BoardLegacyRuntimePreviewListHandlersUtils } from '../renderer/board/legacy-runtime-preview-list-handlers-utils';
import type { BoardLegacySearchUtils } from '../renderer/board/legacy-search-utils';
import type { BoardLegacySelectionUtils } from '../renderer/board/legacy-selection-utils';
import type { BoardLegacyStatusUtils } from '../renderer/board/legacy-status-utils';
import type { BoardLegacyWireupRegistrationUtils } from '../renderer/board/legacy-wireup-registration-utils';
import type { BoardLegacyWireupRuntimeUtils } from '../renderer/board/legacy-wireup-runtime-utils';
import type { BoardLegacyWireupUtils } from '../renderer/board/legacy-wireup-utils';
import type { BoardLegacyUtils } from '../renderer/board/legacy-utils';
import type { BoardLegacyShortcutUtils } from '../renderer/board/legacy-shortcut-utils';
import type { OverlayLegacyInlineVideoUtils } from '../renderer/overlay/legacy-inline-video-utils';
import type { OverlayLegacyBootstrapUtils } from '../renderer/overlay/legacy-bootstrap-utils';
import type { OverlayLegacyCountdownUtils } from '../renderer/overlay/legacy-countdown-utils';
import type { OverlayLegacyMediaDiagnosticsUtils } from '../renderer/overlay/legacy-media-diagnostics';
import type { OverlayLegacyMediaDomUtils } from '../renderer/overlay/legacy-media-dom-utils';
import type { OverlayLegacyMediaFrameUtils } from '../renderer/overlay/legacy-media-frame-utils';
import type { OverlayLegacyMediaFrameLayoutUtils } from '../renderer/overlay/legacy-media-frame-layout-utils';
import type { OverlayLegacyMediaRenderUtils } from '../renderer/overlay/legacy-media-render-utils';
import type { OverlayLegacyMediaOffsetUtils } from '../renderer/overlay/legacy-media-offset-utils';
import type { OverlayLegacyOverlayResetUtils } from '../renderer/overlay/legacy-overlay-reset-utils';
import type { OverlayLegacyPlayFlowUtils } from '../renderer/overlay/legacy-play-flow-utils';
import type { OverlayLegacyPlaybackUtils } from '../renderer/overlay/legacy-playback-utils';
import type { OverlayLegacyPlaybackSessionUtils } from '../renderer/overlay/legacy-playback-session-utils';
import type { OverlayLegacyTextUtils } from '../renderer/overlay/legacy-overlay-text-utils';
import type { OverlayLegacyTweetCardRendererUtils } from '../renderer/overlay/legacy-tweet-card-renderer';
import type { OverlayLegacyTweetCardPlaybackUtils } from '../renderer/overlay/legacy-tweet-card-playback-utils';
import type { OverlayLegacyTweetCardUtils } from '../renderer/overlay/legacy-tweet-card-utils';
import type { OverlayLegacyTwitterWidgetsUtils } from '../renderer/overlay/legacy-twitter-widgets-utils';
import type { OverlayLegacyRuntimeInputsUtils } from '../renderer/overlay/legacy-runtime-inputs-utils';
import type { OverlayLegacyRuntimeMediaFrameHandlersUtils } from '../renderer/overlay/legacy-runtime-media-frame-handlers-utils';
import type { OverlayLegacyRuntimePlaybackCountdownHandlersUtils } from '../renderer/overlay/legacy-runtime-playback-countdown-handlers-utils';
import type { OverlayLegacyRuntimeRenderHandlersUtils } from '../renderer/overlay/legacy-runtime-render-handlers-utils';
import type { OverlayLegacyUtils } from '../renderer/overlay/legacy-utils';

declare global {
  interface Window {
    __boardLegacyUtils?: BoardLegacyUtils;
    __boardLegacyShortcutUtils?: BoardLegacyShortcutUtils;
    __boardLegacyBindingsUtils?: BoardLegacyBindingsUtils;
    __boardLegacyBindingsActionUtils?: BoardLegacyBindingsActionUtils;
    __boardLegacyBootstrapUtils?: BoardLegacyBootstrapUtils;
    __boardLegacyBootstrapOrchestrationUtils?: BoardLegacyBootstrapOrchestrationUtils;
    __boardLegacyCaptureUtils?: BoardLegacyCaptureUtils;
    __boardLegacyCaptureFlowUtils?: BoardLegacyCaptureFlowUtils;
    __boardLegacyCaptureOrchestrationUtils?: BoardLegacyCaptureOrchestrationUtils;
    __boardLegacyRuntimeCaptureHandlersUtils?: BoardLegacyRuntimeCaptureHandlersUtils;
    __boardLegacyDialogFlowUtils?: BoardLegacyDialogFlowUtils;
    __boardLegacyDialogStateUtils?: BoardLegacyDialogStateUtils;
    __boardLegacyDialogOrchestrationUtils?: BoardLegacyDialogOrchestrationUtils;
    __boardLegacyDialogUtils?: BoardLegacyDialogUtils;
    __boardLegacyRuntimeDialogHandlersUtils?: BoardLegacyRuntimeDialogHandlersUtils;
    __boardLegacyEventBindingsUtils?: BoardLegacyEventBindingsUtils;
    __boardLegacyItemActionUtils?: BoardLegacyItemActionUtils;
    __boardLegacyItemActionsOrchestrationUtils?: BoardLegacyItemActionsOrchestrationUtils;
    __boardLegacyItemMetadataActionsUtils?: BoardLegacyItemMetadataActionsUtils;
    __boardLegacyItemUtils?: BoardLegacyItemUtils;
    __boardLegacyKeyboardUtils?: BoardLegacyKeyboardUtils;
    __boardLegacyLifecycleEventUtils?: BoardLegacyLifecycleEventUtils;
    __boardLegacyListActionUtils?: BoardLegacyListActionUtils;
    __boardLegacyListRenderUtils?: BoardLegacyListRenderUtils;
    __boardLegacyListOrchestrationUtils?: BoardLegacyListOrchestrationUtils;
    __boardLegacyLoadSearchUtils?: BoardLegacyLoadSearchUtils;
    __boardLegacyLoadSearchOrchestrationUtils?: BoardLegacyLoadSearchOrchestrationUtils;
    __boardLegacyRenderUtils?: BoardLegacyRenderUtils;
    __boardLegacyPreviewControlsUtils?: BoardLegacyPreviewControlsUtils;
    __boardLegacyPreviewActionUtils?: BoardLegacyPreviewActionUtils;
    __boardLegacyPreviewLayoutUtils?: BoardLegacyPreviewLayoutUtils;
    __boardLegacyPreviewMediaUtils?: BoardLegacyPreviewMediaUtils;
    __boardLegacyPreviewMountUtils?: BoardLegacyPreviewMountUtils;
    __boardLegacyPreviewMessageUtils?: BoardLegacyPreviewMessageUtils;
    __boardLegacyPreviewMessageOrchestrationUtils?: BoardLegacyPreviewMessageOrchestrationUtils;
    __boardLegacyPreviewRenderOrchestrationUtils?: BoardLegacyPreviewRenderOrchestrationUtils;
    __boardLegacyPreviewRenderStateUtils?: BoardLegacyPreviewRenderStateUtils;
    __boardLegacyRuntimeContextUtils?: BoardLegacyRuntimeContextUtils;
    __boardLegacyRuntimeFoundationUtils?: BoardLegacyRuntimeFoundationUtils;
    __boardLegacyRuntimeInputsUtils?: BoardLegacyRuntimeInputsUtils;
    __boardLegacyRuntimeItemLoadHandlersUtils?: BoardLegacyRuntimeItemLoadHandlersUtils;
    __boardLegacyRuntimeLifecycleUtils?: BoardLegacyRuntimeLifecycleUtils;
    __boardLegacyRuntimePreviewListHandlersUtils?: BoardLegacyRuntimePreviewListHandlersUtils;
    __boardLegacySearchUtils?: BoardLegacySearchUtils;
    __boardLegacySelectionUtils?: BoardLegacySelectionUtils;
    __boardLegacyStatusUtils?: BoardLegacyStatusUtils;
    __boardLegacyWireupRegistrationUtils?: BoardLegacyWireupRegistrationUtils;
    __boardLegacyWireupRuntimeUtils?: BoardLegacyWireupRuntimeUtils;
    __boardLegacyWireupUtils?: BoardLegacyWireupUtils;
    __overlayLegacyUtils?: OverlayLegacyUtils;
    __overlayLegacyCountdownUtils?: OverlayLegacyCountdownUtils;
    __overlayLegacyMediaDomUtils?: OverlayLegacyMediaDomUtils;
    __overlayLegacyMediaFrameUtils?: OverlayLegacyMediaFrameUtils;
    __overlayLegacyMediaFrameLayoutUtils?: OverlayLegacyMediaFrameLayoutUtils;
    __overlayLegacyMediaRenderUtils?: OverlayLegacyMediaRenderUtils;
    __overlayLegacyPlayFlowUtils?: OverlayLegacyPlayFlowUtils;
    __overlayLegacyPlaybackUtils?: OverlayLegacyPlaybackUtils;
    __overlayLegacyPlaybackSessionUtils?: OverlayLegacyPlaybackSessionUtils;
    __overlayLegacyBootstrapUtils?: OverlayLegacyBootstrapUtils;
    __overlayLegacyOverlayResetUtils?: OverlayLegacyOverlayResetUtils;
    __overlayLegacyDiagnosticsUtils?: OverlayLegacyMediaDiagnosticsUtils;
    __overlayLegacyMediaOffsetUtils?: OverlayLegacyMediaOffsetUtils;
    __overlayLegacyInlineVideoUtils?: OverlayLegacyInlineVideoUtils;
    __overlayLegacyTextUtils?: OverlayLegacyTextUtils;
    __overlayLegacyTwitterWidgetsUtils?: OverlayLegacyTwitterWidgetsUtils;
    __overlayLegacyTweetCardPlaybackUtils?: OverlayLegacyTweetCardPlaybackUtils;
    __overlayLegacyTweetCardUtils?: OverlayLegacyTweetCardUtils;
    __overlayLegacyTweetCardRendererUtils?: OverlayLegacyTweetCardRendererUtils;
    __overlayLegacyRuntimeInputsUtils?: OverlayLegacyRuntimeInputsUtils;
    __overlayLegacyRuntimeMediaFrameHandlersUtils?: OverlayLegacyRuntimeMediaFrameHandlersUtils;
    __overlayLegacyRuntimePlaybackCountdownHandlersUtils?: OverlayLegacyRuntimePlaybackCountdownHandlersUtils;
    __overlayLegacyRuntimeRenderHandlersUtils?: OverlayLegacyRuntimeRenderHandlersUtils;
  }
}

export {};
